# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='user',
        ),
    ]
